// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdk8p1KF3Yccl9z4H1co0kuVNtOpl_gyg',
    appId: '1:86933222943:web:e2a7b62b07647f05edc72a',
    messagingSenderId: '86933222943',
    projectId: 'login-38a99',
    authDomain: 'login-38a99.firebaseapp.com',
    storageBucket: 'login-38a99.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0liMJLTL9rkNjMyZliTNDAsftWVEZpC4',
    appId: '1:86933222943:android:90c4ea7c4f9dbaf7edc72a',
    messagingSenderId: '86933222943',
    projectId: 'login-38a99',
    storageBucket: 'login-38a99.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdk8p1KF3Yccl9z4H1co0kuVNtOpl_gyg',
    appId: '1:86933222943:web:c1f08d3ba831fc64edc72a',
    messagingSenderId: '86933222943',
    projectId: 'login-38a99',
    authDomain: 'login-38a99.firebaseapp.com',
    storageBucket: 'login-38a99.firebasestorage.app',
  );

}